from langchain_experimental.agents import create_pandas_dataframe_agent
import pandas as pd
from langchain.llms import OpenAI

def query_agent(data, query):

    #Parse teh CSV file and create a Pandas Dataframe from it's contents.
    df = pd.read_csv(data)

    llm = OpenAI()

    #create a pandas data frame agent
    agent = create_pandas_dataframe_agent(llm, df, verbose=True)

    # Run PYTHON_REPL: A python shell used to execute python commands
    #It takes python code generated by a langchain agent as input and outputs the results
    return agent.run(query)

